name: Post to Bluesky

on:
  workflow_dispatch: # Manually run the workflow
  schedule:
    - cron: "0 6 * * *"
      timezone: "Europe/Prague"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 'latest'
      - run: yarn install
      - name: Submit new post
        run: node --no-warnings src/daily.js
        env:
          CALENDAR_APP_HANDLE: "kalendar.bsky.social"
          CALENDAR_APP_PASSWORD: ${{ secrets.CALENDAR_APP_PASSWORD }}